name: TownyMusic
version: '1.0'
main: itsjules.townymusic.TownyMusic
api-version: 1.19
depend: [Towny, NoteBlockAPI]
authors: [ ItsJules_ ]
description: Plays Music inside Towns!
commands:
  togglemusic:
    description: toggles music
